Fix examples warning and add macro
HDFGroup/hdf4 pull request #145
Opened 2023-01-17 20:57 UTC by byrnHDF

Merge from PR #22

2023-01-18 23:52 UTC, derobins commented on hdf/src/hdf.h
> +/* .................................................................. */
I don't think we should put this in the public API. I'm normally against duplicating code, but in this case I'd prefer duplicating it in each set of examples.

2023-01-18 23:54 UTC, derobins commented on hdf/src/hdf.h
> +/* .................................................................. */
In particular, this is going to be visible in the test's tutil.h file, which seems like it has a high probability of causing problems if we were to refactor things.

2023-01-19 02:49 UTC, derobins requested changes
I feel like we should not add the macro to the public API. I don't want to have to support that forever and it'd be confusing to anyone working in the tests (and you KNOW someone is going to use it in the tests at some point...)

2023-01-19 14:12 UTC, byrnHDF commented
> I feel like we should not add the macro to the public API. I don't want to have to support that forever and it'd be confusing to anyone working in the tests (and you KNOW someone is going to use it in the tests at some point...)

Maybe we come up with something better that can be used public. The idea was to show error checking in the examples.

2023-01-19 16:44 UTC, derobins commented
> > I feel like we should not add the macro to the public API. I don't want to have to support that forever and it'd be confusing to anyone working in the tests (and you KNOW someone is going to use it in the tests at some point...)
> 
> Maybe we come up with something better that can be used public. The idea was to show error checking in the examples.

I feel like that's a laudable goal, but I think putting that macro in the public API is asking for trouble.

2023-01-19 21:18 UTC, bmribler commented on hdf/src/hdf.h
> +/* .................................................................. */
Why do you want to put it in hdf.h?  I missed this in the conversation.  A header file can be added in the examples directories for anything used in the examples, like in the dumper.

2023-01-19 21:22 UTC, byrnHDF commented
Redoing.

2023-01-19 21:22 UTC, closed without merging