Fix HDFFR-1607
HDFGroup/hdf4 pull request #297
Opened 2023-02-23 05:28 UTC by bmribler

Description:
    When application called HXsetdir after a read of an external dataset,
    the new setting of the external directory didn't have any effect because
    the library would just use the currently opened file.

    Added a flag to close the file and reopen at the new location if the
    external directory has been changed.  This fix also causes SDreaddata to
    fail in the case where the new external directory is not where the
    external file resides, previously, it just used the old opened file.
    The library now also shows the effect of calling HXsetdir with a NULL
    parameter, which means the external directory will then be the current
    directory.

    Also added/modified utility functions in the test directory.
Platform tested:
    Linux/64 (jelly)

2023-02-23 20:03 UTC, bmribler commented
I'm on it...

2023-02-26 14:22 UTC, byrnHDF approved these changes

2023-02-26 14:31 UTC, byrnHDF commented on mfhdf/test/texternal.c
> +#if defined H4_HAVE_WIN32_API && defined __MINGW32__
Why only mingw with WIN32 API? Why not just WIN32 API?

2023-02-26 14:34 UTC, byrnHDF commented on mfhdf/test/texternal.c
> +#if defined H4_HAVE_WIN32_API && defined __MINGW32__
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/mkdir?view=msvc-170

2023-02-26 14:38 UTC, byrnHDF commented on mfhdf/test/texternal.c
> +#if defined H4_HAVE_WIN32_API && defined __MINGW32__
Another search comment: I had to add the include in the if/endif for MinGW lib: #include <direct.h> /* _mkdir */

2023-02-26 14:39 UTC, byrnHDF requested changes
I think the mkdir #if should just be:
#if defined H4_HAVE_WIN32_API

2023-02-27 14:14 UTC, byrnHDF approved these changes

2023-03-01 05:33 UTC, bmribler commented
Do I need to do anything else on this one?

2023-03-01 14:03 UTC, merged