Fix GH #355 mismatched macros
HDFGroup/hdf4 pull request #358
Opened 2023-05-12 17:49 UTC by byrnHDF

2023-05-12 23:26 UTC, derobins requested changes
We should bring over just the change that is necessary for the patch, not everything in master

2023-05-15 12:32 UTC, byrnHDF commented
> We should bring over just the change that is necessary for the patch, not everything in master

spellcheck wouldn't pass until I fixed the issues.

2023-06-05 16:19 UTC, bmribler approved these changes

2023-06-05 23:16 UTC, derobins approved these changes

2023-06-05 23:17 UTC, merged